/// Flutter icons All_Icons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  All_Icons
///      fonts:
///       - asset: fonts/All_Icons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class All_Icons {
  All_Icons._();

  static const _kFontFam = 'All_Icons';
  static const String? _kFontPkg = null;

  static const IconData category_1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stretching_1 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_1 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_1 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
